name: 'Unreal Game Version Updater'
description: 'Updates an unreal engine based game to the specified version'
inputs:
  version:                            # id of input
    description: 'What to set the version to'
    required: true
  verbose:
    description: 'verbose logging'
    required: false
    default: false
runs:
  using: 'docker'
  image: docker://ghcr.io/benbentwo/unrealgameversionupdater:latest
  args:
    - ${{ inputs.version }}
    - ${{ inputs.verbose && '-v'}}
