name: "docker"
on:
  release:
    types:
      # "released" excludes pre-releases
      # "published" is either a release or a pre-release
      - published
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source code at current commit"
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Build and push"
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          tags: ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}
          push: true
          build-args: |
            VERSION=${{ github.event.release.tag_name }}
